# ==========================================
# FILE LOCATION: database/docker-compose.yml
# ACTION: REPLACE EXISTING docker-compose.yml
# 
# Clean PostgreSQL setup with schema only (no seed data)
# ==========================================

version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nutrition-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nutrition_app
      POSTGRES_USER: nutrition_user
      POSTGRES_PASSWORD: nutrition_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - nutrition-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nutrition-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nutrition.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - nutrition-network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  nutrition-network:
    driver: bridge